flags:
  text:
    integer-simple: false
  QuickCheck:
    base4point8: false
packages:
- ../software/tct-bundle/slogic/

- ../software/tct-bundle/tct-core/
- ../software/tct-bundle/tct-common/

- ../software/tct-bundle/term-rewriting-xml/
- ../software/tct-bundle/tct-trs/
- ../software/tct-bundle/tct-its/

- ../software/tct-bundle/jat/
- ../software/tct-bundle/tct-jbc/
extra-deps:
- List-0.5.2
- QuickCheck-2.8.1
- ansi-terminal-0.6.2.2
- ansi-wl-pprint-0.6.7.3
- async-2.0.2
- colour-2.3.3
- dlist-0.7.1.2
- dotgen-0.4.2
- dyre-0.8.12
- exceptions-0.8.0.2
- executable-path-0.0.3
- fgl-5.5.2.1
- fgl-visualize-0.1.0.1
- ghc-paths-0.1.0.9
- graphviz-2999.18.0.0
- hexpat-0.20.9
- io-storage-0.3
- mtl-2.1.3.1
- multiset-0.2.2
- optparse-applicative-0.11.0.2
- parsec-3.1.9
- polyparse-1.11
- primitive-0.6
- random-1.1
- safe-0.3.9
- set-monad-0.2.0.0
- stm-2.4.4
- temporary-1.2.0.3
- term-rewriting-0.2
- text-1.2.1.3
- tf-random-0.5
- transformers-compat-0.4.0.3
- union-find-array-0.1.0.2
- utf8-string-1.0.1.1
- wl-pprint-text-1.1.0.4
- xdg-basedir-0.2.2
resolver: ghc-7.8.4
